select * from mytable limit 20;

-- WHAT IS TOTAL REVENUE GENERATED BY MALE VS. FEMALE CUSTOMERS?
select gender, sum(purchase_amount) as revenue
from mytable
group by gender;

-- WHICH CUSTOMER USED A DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT?
select customer_id, purchase_amount
from mytable
where discount_applied = 'yes' and (purchase_amount >= (select avg(purchase_amount) from mytable));

-- WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST RIVIEW RATING?
select item_purchased, round(avg(review_rating),2) as average_product_rating
from mytable 
group by item_purchased
order by average_product_rating desc
limit 5 ;

-- COMPARE THE AVERAGE PURCHASE AMOUNT BETWEEN STANDARD AND EXPRESS SHIPPING.
select shipping_type, round(avg(purchase_amount),2) as average
from mytable
where shipping_type in ('standard', 'express')
group by shipping_type;

-- DO SUBSCRIBER CUSTOMER SPEND MORE? COMPARE AVG SPEND AND TOTAL REVENUE BETWEEN SUB AND NON-SUB.
select subscription_status, round(avg(purchase_amount),2) as avg_spend, sum(purchase_amount) as revenue
from mytable
group by subscription_status;

-- WHICH 5 PRODUCT HAVE THE HIGHEST PERSENTAGE OF PURCHASES WITH DISCOUNT APPLIED?
select item_purchased,
round(sum(case when discount_applied = 'yes' then 1 else 0 end)*100/count(*),2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'new'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal'
    end as customer_segment
from mytable)
select customer_segment,count(*) as number_of_customer
from customer_type
group by customer_segment;

-- What are the top 3 most purchased products within each category? 
with item_counts as(
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from mytable
group by category, item_purchased
)
select category, item_purchased, total_orders, item_rank 
from item_counts
where item_rank <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, 
	   count(customer_id) as repeated_buyers
from mytable
where previous_purchases > 5
group by subscription_status;

-- What is the revenue contribution of each age group? 
select age_group,
sum(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;




